# -*- coding: utf-8 -*-
"""All copy for Cosmic Weaponry, Drawn, both languages. build.py reads it."""

NAV = ["vajra", "bell", "bolt", "mekhala", "skyaxe", "sun", "forge", "staff", "rack"]

UI = {
"en": {
"title": "Cosmic Weaponry, Drawn",
"other_title": "อาวุธเทพ วาดด้วยคณิต",
"lang_this": "EN", "lang_other": ("th/", "ไทย", "th"),
"nav_label": "Sections",
"nav": ["Vajra", "Bell", "Bolt", "Mekhala", "Sky axes", "Sun-dust", "Forge", "Staff", "Rack"],
"desc": "A plain-spoken guide to the weapons of the gods, drawn live with math: Indra's vajra, the Buddhist bell, lightning grown cell by cell, Mekhala and Ramasun, stone sky-axes and Tutankhamun's meteorite dagger, the discus and trident ground off the sun, Thor's short-handled hammer and the Monkey King's staff. In English and Thai.",
"card_alt": "A five-pronged golden vajra spinning in a storm, with the title Cosmic Weaponry, Drawn",
"hero_alt": "A golden five-pronged vajra turning slowly while lightning strikes behind it",
"kicker": "A 'splainer · drawn with math",
"lede": "Gods don't carry swords from the hardware store. They carry thunder, sun-dust, sky-iron and diamond. Here's what each one is, where the story comes from, and the arithmetic hiding in it.",
"hero_go": "Start with the thunderbolt",
"cardline": "vajras, bolts, sky-axes and sun-dust",
"what_kick": "Before we start",
"what_h": "What makes a weapon cosmic",
"what_p": [
"Folks in every corner of the world looked up at a storm and figured somebody up there was armed. Lightning got to be a spear, a hammer, an axe, a club with a diamond on each end. The sun got to be a wheel with a sharp edge. Iron that fell out of the sky got made into daggers for kings.",
"So a cosmic weapon is mostly weather and sky, with a god's hand wrapped around it. That's good news for us, because weather and sky obey arithmetic. Every picture on this page is computed while you watch, and most of 'em you can poke.",
"The stories come from the Rigveda, the Puranas, the Mahabharata, Thai dance and manuscript painting, Hesiod, Snorri's Edda and <i>Journey to the West</i>. Where a story has more than one telling, we say which one."],

"vajra_kick": "Indra's thunderbolt · วชิระ",
"vajra_h": "The vajra: thunderbolt and diamond in one word",
"vajra_p": [
"In the Rigveda, the oldest of the Hindu scriptures, the smith-god Tvashtr makes Indra a weapon called the <b>vajra</b>. Indra takes it to Vritra, a serpent who's coiled around the world's waters and won't let 'em go, and strikes him dead. The rivers run again. Put plainly: the storm god hits the drought and the rain comes.",
"Later tellings in the Puranas add a sadder start. Nothing ordinary can kill Vritra, so the gods ask the sage Dadhichi for his bones. He gives 'em, and the vajra is made out of a holy man's backbone.",
"Here's the part the drawing likes: in Sanskrit <i>vajra</i> means both thunderbolt and diamond. The thing nothing can break, and the thing that breaks everything. The shape shows both: a hard ball in the middle, a lotus on each side, and prongs that bend out and come back to meet at a point, like a storm folding in on itself."],
"vajra_note": "Each outer prong is one curve, copied around the shaft every 360°/n. Five prongs means the vajra looks the same after a fifth of a turn.",
"v_prongs": "Prongs on each end", "v_spin": "Spin", "v_strike": "Strike",
"v_sym": "Looks the same every", "v_curves": "Curves drawn", "v_ends": "Points",

"bell_kick": "The Buddhist turn · วัชรยาน",
"bell_h": "A weapon that turned into a prayer",
"bell_p": [
"Buddhism kept the vajra and changed the job. In Tibet and Nepal a monk holds a small vajra (Tibetan <i>dorje</i>) in the right hand and a bell (<i>drilbu</i>, Sanskrit <i>ghanta</i>) in the left. Teachers say the vajra stands for method and compassion, the bell for wisdom, and you need the pair. A whole school is named for it: Vajrayana, the diamond vehicle.",
"The Diamond Sutra's Sanskrit name is <i>Vajracchedika</i>, the one that cuts like a vajra: wisdom that slices through wrong ideas. In Japan the same tool is the <i>kongosho</i>; the three-pronged one below is a <i>sankosho</i>.",
"The Buddha even got a bodyguard who carries one, Vajrapani, \"vajra in hand\". Up in Gandhara, where Greek sculptors had settled after Alexander, they carved Vajrapani looking like Heracles, lion-skin and all.",
"In Thailand Indra is Phra In, and one of his names is <b>วชิราวุธ</b>, \"whose weapon is the vajra\". Brass vajra pendants sold as \"Phra In's weapon\" show up in wichaa's shop listings at ฿39 to ฿89."],
"bell_note": "A bell's overtones don't sit at whole-number steps the way a guitar string's do. This one rings at about 1 : 2.7 : 5.1 : 8.2 of its lowest tone, the rough pattern of a bowl or bell, and the waves beat against each other. That's the shimmer.",
"b_ring": "Ring the bell", "b_tones": "Tones",
"photo": {
"vajra": "Bronze vajra, Thailand or Cambodia.",
"sankosho": "Sankosho, three-pronged vajra, Japan.",
"bell": "Drilbu, Tibetan bell with a vajra handle.",
"vajrapani": "Vajrapani or Heracles, Gandhara, 3rd–4th century.",
"mekhala": "Mekhala with her jewel and Ramasun with his axe, Thai painting.",
"rammasun": "Typhoon Rammasun, 10 May 2008.",
"axe": "Polished stone axe, Neolithic. The kind folks called a thunderstone.",
"dagger": "Tutankhamun's iron dagger. Egyptian Museum, Cairo.",
"fulgurite": "Fulgurite: sand that lightning melted into a glass tube. Sahara, Morocco."},

"bolt_kick": "Physics · ฟ้าผ่า",
"bolt_h": "Grow a bolt, one step at a time",
"bolt_p": [
"Now the weather itself. A lightning channel is a few centimetres across and gets hotter than 27,000 °C, around five times the surface of the sun. It doesn't go straight because the air doesn't break down evenly. The bolt feels its way down in short hops, and each hop goes where the electric pull is strongest, with a little luck thrown in.",
"In 1984 three physicists, Niemeyer, Pietronero and Wiesmann, turned that into a rule you can run. Work out the electric pull at every spot next to the bolt. Pick the next spot at random, weighted by that pull raised to a power η. Add it. Do it again. When the bolt touches ground, the path back up lights up: that's the return stroke, the flash you see.",
"Set η low and the bolt grows bushy, like frost. Set it high and it runs nearly straight for the ground. Somewhere near 1 it branches like lightning in a photograph, and its fractal dimension comes out around 1.7, close to measured bolts. If fractals are your thing, the <a href=\"https://nanobotco.github.io/fractals/\">fractals 'splainer</a> has more."],
"bolt_note": "Every grown spot is a cell in a grid; the pull is worked out by relaxing the grid over and over until it settles. Dimension is a box count: how the number of boxes the bolt touches changes as the boxes shrink.",
"l_eta": "η, how much the bolt follows the pull", "l_grow": "Grow a bolt", "l_steps": "Hops", "l_dim": "Dimension, box count", "l_tips": "Branch tips",

"mek_kick": "The Thai storm · เมขลา–รามสูร",
"mek_h": "Mekhala's jewel and Ramasun's axe",
"mek_p": [
"Thai grandparents tell it this way. Up in the clouds, Mekhala, keeper of the seas, plays with a magic jewel, tossing it and flashing it. The giant Ramasun wants that jewel bad. He hurls his diamond axe at her. She flashes the jewel in his eyes, and the axe misses. The flash is lightning. The crash of the axe is thunder. The pair dance it on the Thai stage, and they've opened shows since Ayutthaya times.",
"Notice the order: flash first, crash after. That part's dead right. Light covers a kilometre in about three millionths of a second. Sound needs about three seconds. So count from the flash to the boom, divide by three, and you've got kilometres to the strike. (In miles, divide by five.)",
"Thailand gave both names to the list for Pacific storms: there have been typhoons called Rammasun and storms called Mekkhala."],
"mek_note": "Sound speed taken as 343 m/s, air at 20 °C. Thunder carries roughly 15–25 km on a quiet night, so past about a minute you won't hear it at all.",
"m_dist": "Strike distance", "m_flash": "Throw the axe", "m_count": "Count it yourself", "m_tap1": "Tap at the flash", "m_tap2": "Tap at the boom",
"m_delay": "Flash to boom", "m_km": "Distance", "m_light": "Light took", "m_mek": "Mekhala", "m_ram": "Ramasun", "m_you": "you",

"ax_kick": "Stones and iron from the sky · ขวานฟ้า",
"ax_h": "Sky-axes and a king's star-iron dagger",
"ax_p": [
"Farmers ploughing a field would turn up a smooth, sharp stone shaped like an axe head. Where'd it come from? Down with the lightning, they reckoned. Thai has a word for it, <b>ขวานฟ้า</b>, sky-axe, and the Royal Institute dictionary says it straight: a stone axe from the Stone Age, believed to fall from the sky when lightning strikes. The Romans called 'em <i>ceraunia</i>; Pliny wrote they were found only where a thunderbolt had hit. In Java they're \"lightning's teeth\". In France folks tucked 'em under the doorsill to keep the house from burning.",
"They're tools, of course: Neolithic axes, ground and polished by people thousands of years back. But some weapons did come from the sky. The iron dagger buried with Tutankhamun, 3,300 years ago, was tested in 2016 with X-rays. Its blade is about 10.8% nickel and 0.58% cobalt. Iron smelted from ore on Earth runs 4% nickel or less. That blade is a meteorite.",
"Cut a nickel-iron meteorite, polish it, wash it in acid, and a criss-cross of long crystal bands appears, the Widmanstätten pattern. It grows only when the metal cools somewhere between a tenth of a degree and ten degrees every thousand years, deep inside an asteroid. No forge on Earth can wait that long."],
"ax_note": "The bands follow the faces of an octahedron, so a flat slice cuts them in three or four directions depending on the angle. More nickel makes thinner bands. Under about 6% nickel or over about 16%, a meteorite shows no bands at all.",
"x_ni": "Nickel in the iron", "x_angle": "Angle of the slice", "x_verdict": "Verdict", "x_earth": "Earth iron, from ore", "x_sky": "Sky iron, a meteorite", "x_odd": "Odd for either", "x_hexa": "no bands: too little nickel", "x_atax": "no bands: too much nickel", "x_bands": "Band width",

"sun_kick": "Ground off the sun · จักรและตรีศูล",
"sun_h": "A discus and a trident, ground off the sun",
"sun_p": [
"The Vishnu Purana has a family story. Sanjna, daughter of the divine craftsman Vishvakarma (Thai: พระวิษณุกรรม), is married to the Sun, and she can't stand the glare. So her daddy puts the Sun on his lathe and grinds some of the shine off him. He gets an eighth. The rest won't come off.",
"Out of that glowing dust he makes four things: Vishnu's discus, the Sudarshana chakra; Shiva's trident, the trishula; the flying palace Pushpaka (Thai: บุษบก); and the spear of Skanda.",
"Thai readers have seen two of those every day without thinking of the sun. The emblem of the Chakri dynasty is a discus with a trident through it: Vishnu's weapon and Shiva's, made from the same sun-dust."],
"sun_note": "A disc's light goes with its area, the square of its radius. Take off an eighth of the light and the radius only shrinks to √(7/8), about 93.5% of where it started.",
"s_grind": "Grind the sun", "s_light": "Sun's light left", "s_radius": "Radius", "s_made": "Made so far",
"s_things": ["discus", "trident", "Pushpaka", "Skanda's spear"],
"s_teeth": "Teeth on the discus",

"forge_kick": "Smiths of the gods · ค้อนและสายฟ้า",
"forge_h": "Forged by one-eyed giants and a pair of dwarfs",
"forge_p": [
"In Greece, Hesiod's <i>Theogony</i> tells it: Zeus frees the Cyclopes, and they make him the thunderbolt. Their names are the weather report: Brontes, Thunder; Steropes, Lightning; Arges, Bright.",
"Up north, Snorri's Edda tells how Loki bet his head that the dwarf brothers Eitri and Brokkr couldn't out-make another smith. Eitri worked the fire, Brokkr pumped the bellows and must not stop. A fly (Loki in disguise, most folks figure) bit Brokkr's hand, then his neck, then his eyelid, and on that last bite he let go of the bellows for a breath. The hammer came out with its handle too short. That's Mjölnir, and it still won the bet: it hits anything, and it comes back to Thor's hand.",
"Your turn. Hold the bellows down. The fly'll come. Every moment you let go costs the handle."],
"forge_note": "The handle starts at 60 cm and loses length for every tenth of a second the fire goes untended. A thrown hammer comes home along a loop: out, around, back, a curve called a limaçon.",
"f_pump": "Hold to pump the bellows", "f_throw": "Throw it", "f_reset": "New forge", "f_handle": "Handle", "f_heat": "Forge heat", "f_bites": "Fly bites",

"staff_kick": "The Monkey King · กระบองซุนหงอคง",
"staff_h": "Eight tonnes that fit in an ear",
"staff_p": [
"In chapter 3 of <i>Journey to the West</i>, Sun Wukong, the Monkey King, goes down to the Dragon King of the Eastern Sea shopping for a weapon. He finds an iron pillar stamped with its own weight: 13,500 <i>jin</i>. In the Ming dynasty a jin ran about 600 grams, so that's around 8 tonnes. It shrinks or grows on his word. He first shrinks it to a bit taller than himself and as thick as a rice bowl, and when he's not fighting it's a needle tucked inside his ear.",
"The weight doesn't change. So squeeze 8 tonnes into a smaller staff and it gets denser. Slide it and watch: stretched up toward heaven it's lighter than air; as the pillar in the sea it's a little lighter than iron; in his hand it's sixteen times as dense as osmium, the densest metal; as a needle it outdoes the core of a white dwarf star. The <a href=\"https://nanobotco.github.io/black-holes/\">black holes 'splainer</a> picks up from there."],
"staff_note": "Mass held at 13,500 × 0.597 kg = 8,057 kg. The staff keeps the same shape as it shrinks, a rod 12 times as long as it is wide, about its shape in his hand, so its volume goes with the cube of its length.",
"t_len": "Length of the staff", "t_density": "Density", "t_like": "As dense as", "t_vs_water": "Times water",

"rack_kick": "The rack · คลังอาวุธ",
"rack_h": "More from the armoury",
"rack_p": ["One line each, with where the story lives."],
"rack": [
["Vajra · วชิระ", "Indra", "Thunderbolt and diamond. Made by Tvashtr in the Rigveda; from Dadhichi's bones in the Puranas.", "vajra"],
["Sudarshana chakra · จักร", "Vishnu", "A spinning discus with a sharp rim, ground from the sun. Vishnu Purana 3.2.", "chakra"],
["Trishula · ตรีศูล", "Shiva", "The trident, from the same sun-dust. Three prongs, read as three of almost anything.", "trident"],
["Keraunos · สายฟ้าซูส", "Zeus", "The thunderbolt the Cyclopes made him. Hesiod, Theogony.", "keraunos"],
["Mjölnir · มยอลนีร์", "Thor", "Short handle, never misses, comes home. Snorri's Edda.", "hammer"],
["Gungnir · กุงนีร์", "Odin", "A spear made by the sons of Ivaldi, from the same contest as the hammer.", "spear"],
["Ruyi Jingu Bang · กระบองวิเศษ", "Sun Wukong", "13,500 jin, grows or shrinks on command. Journey to the West, ch. 3.", "staff"],
["Ramasun's axe · ขวานรามสูร", "Ramasun", "Thrown at Mekhala; its crash is the thunder. Thai dance and painting.", "axe"],
["Mekhala's jewel · แก้วมณีเมขลา", "Mekhala", "Flashed in the giant's eyes; its light is the lightning.", "jewel"],
["Brahmastra · พรหมาสตร์", "Brahma", "A weapon called down with a verse, too strong to use lightly. Mahabharata.", "astra"],
["Gandiva · คาณฑีวะ", "Arjuna", "The bow Arjuna gets from the fire god Agni before the Khandava forest burns. Mahabharata.", "bow"],
["Kusanagi · คุซานางิ", "Susanoo", "A sword found in the tail of the eight-headed serpent Orochi. Kojiki, 712.", "sword"]],

"words_h": "Words",
"src_h": "Sources",
"src_p": "Stories from translations of the texts named; numbers from the papers and agencies below; pictures from Wikimedia Commons with their licences.",
"foot": "Text CC BY 4.0, NaNoBotCo. Code MIT. Photographs keep their own licences.",
"js": {"sym": "{n}°", "km": "km", "mi": "mi", "s": "s", "us": "µs", "cm": "cm", "m": "m", "kgm3": "kg/m³",
 "like": [[0.01, "thin air"], [1.2, "air"], [100, "cork"], [1000, "water"], [2700, "aluminium"], [7874, "iron"], [19300, "gold"], [22590, "osmium, the densest metal"], [1e5, "nothing on Earth"], [1e7, "a white dwarf's outer layers"], [1e9, "a white dwarf's core"], [1e14, "past a white dwarf"], [4e17, "a neutron star"]],
 "tap": "Tap", "wait": "watch the sky…", "again": "Again", "hit": "Hit!", "miss": "the fire cooled", "fly": "the fly bit", "done": "done", "ring": "Ring the bell"}
},

"th": {
"title": "อาวุธเทพ วาดด้วยคณิต",
"other_title": "Cosmic Weaponry, Drawn",
"lang_this": "ไทย", "lang_other": ("../", "EN", "en"),
"nav_label": "หัวข้อ",
"nav": ["วชิระ", "กระดิ่ง", "สายฟ้า", "เมขลา", "ขวานฟ้า", "ฝุ่นตะวัน", "เตาตีเหล็ก", "กระบอง", "คลังอาวุธ"],
"desc": "เล่าอาวุธของเทพแบบบ้าน ๆ วาดสด ๆ ด้วยคณิตศาสตร์ วชิระของพระอินทร์ กระดิ่งวัชรยาน สายฟ้าที่งอกทีละช่อง เมขลากับรามสูร ขวานฟ้ากับกริชเหล็กอุกกาบาตของตุตันคามุน จักรกับตรีศูลที่กลึงออกจากดวงอาทิตย์ ค้อนด้ามสั้นของธอร์ และกระบองของซุนหงอคง มีทั้งภาษาไทยและอังกฤษ",
"card_alt": "วชิระห้าแฉกสีทองหมุนอยู่กลางพายุ พร้อมชื่อ อาวุธเทพ วาดด้วยคณิต",
"hero_alt": "วชิระห้าแฉกสีทองหมุนช้า ๆ มีฟ้าผ่าอยู่ด้านหลัง",
"kicker": "เล่าให้ฟัง · วาดด้วยคณิต",
"lede": "เทพไม่ได้ซื้ออาวุธจากร้านฮาร์ดแวร์ เขาถือฟ้าร้อง ฝุ่นดวงอาทิตย์ เหล็กจากฟ้า และเพชร มาดูกันว่าแต่ละอย่างคืออะไร เรื่องมาจากไหน และมีเลขอะไรซ่อนอยู่",
"hero_go": "เริ่มที่วชิระ",
"cardline": "วชิระ สายฟ้า ขวานฟ้า ฝุ่นตะวัน",
"what_kick": "ก่อนเริ่ม",
"what_h": "อาวุธแบบไหนถึงเรียกว่าอาวุธเทพ",
"what_p": [
"คนทุกมุมโลกมองพายุแล้วคิดเหมือนกันว่าข้างบนนั้นต้องมีใครถืออาวุธอยู่ ฟ้าผ่าเลยกลายเป็นหอก เป็นค้อน เป็นขวาน เป็นกระบองที่มีเพชรสองหัว ดวงอาทิตย์กลายเป็นจักรคม ๆ เหล็กที่ตกลงมาจากฟ้าก็ถูกตีเป็นกริชให้กษัตริย์",
"อาวุธเทพส่วนใหญ่จึงคือดินฟ้าอากาศที่มีมือเทพจับไว้ ข่าวดีคือดินฟ้าอากาศเชื่อฟังเลขคณิต ทุกภาพในหน้านี้คำนวณสด ๆ ตอนที่คุณดู และส่วนใหญ่กดเล่นได้",
"เรื่องเล่ามาจากฤคเวท ปุราณะ มหาภารตะ นาฏศิลป์และจิตรกรรมไทย เฮสิโอด เอ็ดดาของสนอร์รี และไซอิ๋ว เรื่องไหนเล่าได้หลายแบบ เราบอกไว้ว่าใช้ฉบับไหน"],

"vajra_kick": "สายฟ้าของพระอินทร์ · Vajra",
"vajra_h": "วชิระ คำเดียวที่แปลได้ทั้งสายฟ้าและเพชร",
"vajra_p": [
"ในฤคเวท คัมภีร์เก่าแก่ที่สุดของฮินดู เทพช่างชื่อตวัษฏฤสร้างอาวุธให้พระอินทร์ เรียกว่า <b>วชิระ</b> พระอินทร์ถือไปฟาดวฤตระ งูยักษ์ที่ขดรัดน้ำของโลกไว้ไม่ยอมปล่อย วฤตระตาย แม่น้ำไหลอีกครั้ง พูดง่าย ๆ คือเทพแห่งพายุฟาดความแล้ง แล้วฝนก็ตก",
"ปุราณะยุคหลังเล่าต้นเรื่องที่เศร้ากว่านั้น ไม่มีอะไรธรรมดาฆ่าวฤตระได้ เหล่าเทพจึงไปขอกระดูกจากฤๅษีทธีจิ ท่านยอมให้ วชิระจึงทำจากกระดูกสันหลังของนักบวช",
"ส่วนที่ภาพชอบคือ ในภาษาสันสกฤต <i>วชฺร</i> แปลได้ทั้งสายฟ้าและเพชร ของที่ไม่มีอะไรทำลายได้ กับของที่ทำลายได้ทุกอย่าง รูปร่างก็บอกทั้งสองอย่าง ลูกกลมแข็งตรงกลาง ดอกบัวสองข้าง แฉกที่โค้งออกแล้วโค้งกลับมาบรรจบกันที่ปลาย เหมือนพายุที่ม้วนเข้าหาตัวเอง"],
"vajra_note": "แฉกด้านนอกแต่ละแฉกคือเส้นโค้งเส้นเดียว ก๊อปปี้ไปรอบแกนทุก 360°/n วชิระห้าแฉกหมุนไปหนึ่งในห้ารอบแล้วหน้าตาเหมือนเดิม",
"v_prongs": "จำนวนแฉกแต่ละข้าง", "v_spin": "หมุน", "v_strike": "ผ่า",
"v_sym": "หมุนครบรูปทุก ๆ", "v_curves": "เส้นโค้งที่วาด", "v_ends": "ปลายแหลม",

"bell_kick": "ทางพุทธ · Vajrayana",
"bell_h": "อาวุธที่กลายเป็นเครื่องสวดมนต์",
"bell_p": [
"พุทธศาสนาเก็บวชิระไว้แต่เปลี่ยนหน้าที่ ในทิเบตและเนปาล พระถือวชิระเล็ก ๆ (ภาษาทิเบตเรียก <i>ดอร์เจ</i>) ไว้มือขวา และกระดิ่ง (<i>ดริลบุ</i> สันสกฤตว่า <i>ฆัณฏา</i>) ไว้มือซ้าย ครูบาอาจารย์สอนว่าวชิระคืออุบายและกรุณา กระดิ่งคือปัญญา ต้องมีคู่กัน นิกายหนึ่งตั้งชื่อตามนี้ทั้งนิกาย คือวัชรยาน ยานเพชร",
"ชื่อสันสกฤตของวัชรสูตรคือ <i>วัชรัจเฉทิกา</i> แปลว่าสิ่งที่ตัดได้ดั่งวชิระ คือปัญญาที่ตัดความเห็นผิด ในญี่ปุ่นของชิ้นเดียวกันเรียกว่า <i>คงโงโช</i> แบบสามแฉกในภาพข้างล่างเรียกว่า <i>ซังโกะโช</i>",
"พระพุทธเจ้ายังมีองครักษ์ที่ถือวชิระด้วย ชื่อวัชรปาณี แปลว่า \"วชิระในมือ\" ที่คันธาระ ซึ่งช่างปั้นกรีกมาตั้งรกรากหลังยุคอเล็กซานเดอร์ เขาปั้นวัชรปาณีให้หน้าตาเหมือนเฮอร์คิวลีส มีหนังสิงโตคลุมด้วย",
"ในไทย พระอินทร์มีพระนามหนึ่งว่า <b>วชิราวุธ</b> แปลว่า \"ผู้มีวชิระเป็นอาวุธ\" จี้วชิระทองเหลืองที่ขายในชื่อ \"อาวุธประจำกายพระอินทร์\" มีอยู่ในรายการร้านค้าที่ wichaa เก็บไว้ ราคา ฿39 ถึง ฿89"],
"bell_note": "เสียงก้องของกระดิ่งไม่ได้เรียงเป็นขั้นเลขจำนวนเต็มแบบสายกีตาร์ ใบนี้ดังที่ราว 1 : 2.7 : 5.1 : 8.2 เท่าของเสียงต่ำสุด ซึ่งเป็นรูปแบบคร่าว ๆ ของขันหรือระฆัง คลื่นเลยตีกันไปมา นั่นคือเสียงวิ้ง ๆ ที่ได้ยิน",
"b_ring": "สั่นกระดิ่ง", "b_tones": "เสียง",
"photo": {
"vajra": "วชิระสำริด ไทยหรือกัมพูชา",
"sankosho": "ซังโกะโช วชิระสามแฉก ญี่ปุ่น",
"bell": "ดริลบุ กระดิ่งทิเบตด้ามวชิระ",
"vajrapani": "วัชรปาณีหรือเฮอร์คิวลีส คันธาระ ศตวรรษที่ 3–4",
"mekhala": "เมขลาล่อแก้ว รามสูรถือขวาน จิตรกรรมไทย",
"rammasun": "ไต้ฝุ่นรามสูร 10 พฤษภาคม 2008",
"axe": "ขวานหินขัดยุคหินใหม่ แบบที่ชาวบ้านเรียกว่าขวานฟ้า",
"dagger": "กริชเหล็กของตุตันคามุน พิพิธภัณฑ์อียิปต์ ไคโร",
"fulgurite": "ฟัลกูไรต์ ทรายที่ฟ้าผ่าหลอมเป็นหลอดแก้ว ทะเลทรายซาฮารา โมร็อกโก"},

"bolt_kick": "ฟิสิกส์ · Lightning",
"bolt_h": "ปลูกสายฟ้าทีละก้าว",
"bolt_p": [
"มาดูดินฟ้าอากาศตัวจริงกัน ช่องฟ้าผ่ากว้างแค่ไม่กี่เซนติเมตร แต่ร้อนเกิน 27,000 °C ราวห้าเท่าของผิวดวงอาทิตย์ มันไม่ลงมาตรง ๆ เพราะอากาศไม่ได้แตกตัวเท่ากันทุกที่ สายฟ้าคลำทางลงมาทีละช่วงสั้น ๆ แต่ละช่วงไปทางที่แรงดึงไฟฟ้ามากที่สุด บวกดวงนิดหน่อย",
"ปี 1984 นักฟิสิกส์สามคน นีไมเยอร์ ปีเอโตรเนโร และวีสมันน์ ทำเรื่องนี้ให้เป็นกฎที่รันได้ หาแรงดึงไฟฟ้าทุกจุดที่อยู่ติดกับสายฟ้า สุ่มจุดต่อไปโดยให้น้ำหนักตามแรงดึงยกกำลัง η เติมจุดนั้นเข้าไป แล้วทำซ้ำ พอสายฟ้าแตะพื้น เส้นทางย้อนกลับขึ้นไปจะสว่างวาบ นั่นคือจังหวะที่เราเห็นแสงฟ้าแลบ",
"ตั้ง η ต่ำ สายฟ้าจะแตกกิ่งฟูเหมือนน้ำค้างแข็ง ตั้งสูง มันจะพุ่งเกือบตรงลงพื้น แถว ๆ 1 จะแตกกิ่งเหมือนฟ้าผ่าในรูปถ่าย และมิติแฟร็กทัลออกมาราว 1.7 ใกล้กับที่วัดจากฟ้าผ่าจริง ใครชอบแฟร็กทัล ไปเล่นต่อได้ที่ <a href=\"https://nanobotco.github.io/fractals/th/\">เล่นกับแฟร็กทัล</a>"],
"bolt_note": "แต่ละจุดที่งอกคือช่องหนึ่งในตาราง แรงดึงคำนวณโดยปรับค่าในตารางซ้ำไปเรื่อย ๆ จนนิ่ง มิตินับด้วยกล่อง ดูว่าจำนวนกล่องที่สายฟ้าแตะเปลี่ยนไปเท่าไรเมื่อกล่องเล็กลง",
"l_eta": "η ยิ่งมาก สายฟ้ายิ่งตามแรงดึง", "l_grow": "ปลูกสายฟ้า", "l_steps": "จำนวนก้าว", "l_dim": "มิติ นับกล่อง", "l_tips": "ปลายกิ่ง",

"mek_kick": "พายุแบบไทย · Mekhala and Ramasun",
"mek_h": "แก้วของเมขลา ขวานของรามสูร",
"mek_p": [
"ผู้ใหญ่เล่าให้ฟังว่า บนก้อนเมฆ นางเมขลาผู้รักษามหาสมุทรเล่นแก้ววิเศษ โยนบ้าง ล่อแสงบ้าง ยักษ์รามสูรอยากได้แก้วนั้นนัก จึงขว้างขวานเพชรใส่นาง นางล่อแก้วให้แสงแยงตา ขวานพลาดเป้า แสงแก้วคือฟ้าแลบ เสียงขวานคือฟ้าร้อง ระบำเมขลา–รามสูรเป็นชุดเบิกโรงมาตั้งแต่สมัยอยุธยา",
"สังเกตลำดับ แสงมาก่อน เสียงตามมา ข้อนี้ถูกเป๊ะ แสงวิ่งหนึ่งกิโลเมตรใช้ราวสามในล้านวินาที เสียงใช้ราวสามวินาที นับตั้งแต่ฟ้าแลบจนได้ยินเสียง หารด้วยสาม ก็ได้ระยะเป็นกิโลเมตร",
"ไทยส่งทั้งสองชื่อเข้ารายชื่อพายุแปซิฟิก จึงมีไต้ฝุ่นชื่อรามสูร และพายุชื่อเมขลา"],
"mek_note": "ใช้ความเร็วเสียง 343 เมตรต่อวินาที อากาศ 20 °C คืนที่เงียบ ฟ้าร้องได้ยินไกลราว 15–25 กิโลเมตร เกินราวหนึ่งนาทีก็จะไม่ได้ยินแล้ว",
"m_dist": "ระยะฟ้าผ่า", "m_flash": "ขว้างขวาน", "m_count": "ลองนับเอง", "m_tap1": "แตะตอนฟ้าแลบ", "m_tap2": "แตะตอนได้ยินเสียง",
"m_delay": "แลบถึงร้อง", "m_km": "ระยะ", "m_light": "แสงใช้เวลา", "m_mek": "เมขลา", "m_ram": "รามสูร", "m_you": "เรา",

"ax_kick": "หินและเหล็กจากฟ้า · Sky-axes",
"ax_h": "ขวานฟ้า กับกริชเหล็กดาวตกของฟาโรห์",
"ax_p": [
"ชาวนาไถนาแล้วเจอหินเรียบคมรูปหัวขวาน มาจากไหน ก็ต้องตกมากับฟ้าผ่าสิ ภาษาไทยมีคำเรียกว่า <b>ขวานฟ้า</b> พจนานุกรมราชบัณฑิตยสถานให้ความหมายตรง ๆ ว่าขวานหินยุคหิน ที่เชื่อกันว่าตกลงมาจากฟ้าเวลาฟ้าผ่า ชาวโรมันเรียกว่า <i>เคราอูเนีย</i> พลินีเขียนว่าพบได้เฉพาะที่ที่สายฟ้าลง ในชวาเรียกว่า \"ฟันของสายฟ้า\" ในฝรั่งเศสเอาไปซุกไว้ใต้ธรณีประตูกันบ้านไฟไหม้",
"ที่จริงมันคือเครื่องมือ ขวานยุคหินใหม่ที่คนเมื่อหลายพันปีก่อนฝนและขัดจนเรียบ แต่อาวุธบางชิ้นมาจากฟ้าจริง ๆ กริชเหล็กที่ฝังไปกับตุตันคามุนเมื่อ 3,300 ปีก่อน ถูกตรวจด้วยรังสีเอกซ์ในปี 2016 ใบกริชมีนิกเกิลราว 10.8% และโคบอลต์ 0.58% เหล็กที่ถลุงจากแร่บนโลกมีนิกเกิลไม่เกิน 4% ใบกริชนั้นคืออุกกาบาต",
"ตัดอุกกาบาตเหล็กนิกเกิล ขัดมัน ล้างกรด จะเห็นแถบผลึกยาว ๆ ไขว้กันเป็นลาย เรียกว่าลายวิดมันชเตตเทิน ลายนี้เกิดได้เฉพาะเมื่อโลหะเย็นลงช้า ๆ ราวหนึ่งในสิบองศาถึงสิบองศาทุกพันปี ลึกอยู่ในดาวเคราะห์น้อย ไม่มีเตาไหนบนโลกรอได้นานขนาดนั้น"],
"ax_note": "แถบเรียงตามหน้าของทรงแปดหน้า แผ่นที่ตัดตรง ๆ จึงเห็นแถบสามหรือสี่ทิศ แล้วแต่มุมที่ตัด นิกเกิลยิ่งมาก แถบยิ่งบาง ถ้านิกเกิลต่ำกว่าราว 6% หรือเกินราว 16% อุกกาบาตจะไม่มีแถบเลย",
"x_ni": "นิกเกิลในเหล็ก", "x_angle": "มุมที่ตัด", "x_verdict": "ผลตรวจ", "x_earth": "เหล็กโลก ถลุงจากแร่", "x_sky": "เหล็กฟ้า อุกกาบาต", "x_odd": "แปลกทั้งสองแบบ", "x_hexa": "ไม่มีแถบ นิกเกิลน้อยไป", "x_atax": "ไม่มีแถบ นิกเกิลมากไป", "x_bands": "ความกว้างแถบ",

"sun_kick": "กลึงดวงอาทิตย์ · Sun-dust",
"sun_h": "จักรและตรีศูล กลึงออกจากดวงอาทิตย์",
"sun_p": [
"วิษณุปุราณะมีเรื่องในครอบครัว นางสัญชญา ลูกสาวของพระวิษณุกรรม เทพแห่งช่าง แต่งงานกับพระอาทิตย์ แต่ทนแสงจ้าไม่ไหว พ่อเลยเอาพระอาทิตย์ขึ้นแท่นกลึง ขูดแสงออกไปส่วนหนึ่ง ได้หนึ่งในแปด ที่เหลือขูดไม่ออก",
"จากฝุ่นเรืองแสงนั้น ท่านสร้างของสี่อย่าง จักรสุทรรศน์ของพระนารายณ์ ตรีศูลของพระศิวะ บุษบกวิมานที่บินได้ และหอกของพระขันธกุมาร",
"คนไทยเห็นสองอย่างในนั้นทุกวันโดยไม่ได้นึกถึงดวงอาทิตย์ ตราราชวงศ์จักรีคือจักรที่มีตรีศูลสอดอยู่ อาวุธพระนารายณ์กับอาวุธพระศิวะ ทำจากฝุ่นดวงอาทิตย์กองเดียวกัน"],
"sun_note": "แสงของจานกลมขึ้นกับพื้นที่ คือรัศมียกกำลังสอง ขูดแสงออกหนึ่งในแปด รัศมีหดลงเหลือแค่ √(7/8) ราว 93.5% ของเดิม",
"s_grind": "กลึงดวงอาทิตย์", "s_light": "แสงที่เหลือ", "s_radius": "รัศมี", "s_made": "สร้างแล้ว",
"s_things": ["จักร", "ตรีศูล", "บุษบก", "หอกพระขันธกุมาร"],
"s_teeth": "ฟันของจักร",

"forge_kick": "ช่างของเทพ · Smiths",
"forge_h": "ตีโดยยักษ์ตาเดียว กับคนแคระสองพี่น้อง",
"forge_p": [
"ทางกรีก เฮสิโอดเล่าไว้ในเทโอโกเนียว่า ซูสปลดปล่อยพวกไซคลอปส์ แล้วพวกนี้ตีสายฟ้าให้ ชื่อของพวกเขาก็คือพยากรณ์อากาศ บรอนเทส แปลว่าฟ้าร้อง สเตโรเปส แปลว่าฟ้าแลบ อาร์เกส แปลว่าสว่าง",
"ทางเหนือ เอ็ดดาของสนอร์รีเล่าว่าโลกิพนันหัวตัวเองว่าคนแคระสองพี่น้อง ไอทรีกับบรอคร์ ทำของได้ไม่สวยเท่าช่างอีกเจ้า ไอทรีดูไฟ บรอคร์สูบเครื่องเป่าลมห้ามหยุด แมลงวันตัวหนึ่ง (คนส่วนใหญ่ว่าเป็นโลกิแปลงร่าง) กัดมือบรอคร์ กัดคอ แล้วกัดเปลือกตา ครั้งสุดท้ายเขาปล่อยมือจากที่สูบลมไปชั่วอึดใจ ค้อนออกมาด้ามสั้นเกิน นั่นคือมยอลนีร์ แต่ก็ยังชนะพนัน เพราะขว้างโดนทุกอย่าง แล้วบินกลับมาที่มือธอร์",
"ตาคุณแล้ว กดที่สูบลมค้างไว้ แมลงวันจะมา ทุกจังหวะที่ปล่อยมือ ด้ามจะสั้นลง"],
"forge_note": "ด้ามเริ่มที่ 60 ซม. และสั้นลงทุกหนึ่งในสิบวินาทีที่ไฟไม่มีคนดู ค้อนที่ขว้างออกไปจะกลับบ้านตามวงโค้ง ออกไป อ้อม แล้วกลับ เป็นเส้นโค้งที่เรียกว่าลิมาซง",
"f_pump": "กดค้างเพื่อสูบลม", "f_throw": "ขว้าง", "f_reset": "เริ่มเตาใหม่", "f_handle": "ด้าม", "f_heat": "ความร้อนเตา", "f_bites": "แมลงวันกัด",

"staff_kick": "ซุนหงอคง · The Monkey King",
"staff_h": "แปดตันที่เก็บไว้ในหูได้",
"staff_p": [
"ในไซอิ๋ว ตอนที่ 3 ซุนหงอคงลงไปหาพญามังกรทะเลตะวันออกเพื่อหาอาวุธ เจอเสาเหล็กต้นหนึ่งที่สลักน้ำหนักตัวเองไว้ 13,500 ชั่ง สมัยราชวงศ์หมิงหนึ่งชั่งราว 600 กรัม รวมแล้วราว 8 ตัน มันย่อหรือขยายตามคำสั่ง ครั้งแรกเขาย่อให้สูงกว่าตัวเองนิดหน่อย หนาเท่าชามข้าว เวลาไม่ได้รบก็ย่อเป็นเข็มเก็บไว้ในหู",
"น้ำหนักไม่เปลี่ยน อัด 8 ตันลงในกระบองที่เล็กลง มันก็ยิ่งแน่น เลื่อนดู ยืดสูงเสียดฟ้า เบากว่าอากาศ ขนาดเสาในทะเล เบากว่าเหล็กนิดหน่อย ขนาดที่ถืออยู่ในมือ แน่นเป็นสิบหกเท่าของออสเมียม โลหะที่แน่นที่สุด พอเป็นเข็ม แน่นกว่าแกนดาวแคระขาว ต่อจากนั้นไปอ่าน <a href=\"https://nanobotco.github.io/black-holes/\">หลุมดำ</a> ได้เลย"],
"staff_note": "มวลคงที่ 13,500 × 0.597 กก. = 8,057 กก. กระบองย่อโดยคงรูปทรง ยาวเป็น 12 เท่าของความหนา ราวรูปทรงตอนอยู่ในมือ ปริมาตรจึงแปรตามความยาวยกกำลังสาม",
"t_len": "ความยาวกระบอง", "t_density": "ความหนาแน่น", "t_like": "แน่นพอ ๆ กับ", "t_vs_water": "เท่าของน้ำ",

"rack_kick": "คลังอาวุธ · The rack",
"rack_h": "อาวุธอื่น ๆ ในคลัง",
"rack_p": ["อย่างละบรรทัด พร้อมบอกว่าเรื่องมาจากไหน"],
"rack": [
["วชิระ · Vajra", "พระอินทร์", "สายฟ้าและเพชร ตวัษฏฤสร้างในฤคเวท ทำจากกระดูกฤๅษีทธีจิในปุราณะ", "vajra"],
["จักร · Sudarshana", "พระนารายณ์", "จักรหมุนขอบคม กลึงจากดวงอาทิตย์ วิษณุปุราณะ 3.2", "chakra"],
["ตรีศูล · Trishula", "พระศิวะ", "สามง่ามจากฝุ่นตะวันกองเดียวกัน สามแฉกตีความได้เป็นสามอะไรก็ได้", "trident"],
["สายฟ้าซูส · Keraunos", "ซูส", "สายฟ้าที่ไซคลอปส์ตีให้ เทโอโกเนียของเฮสิโอด", "keraunos"],
["มยอลนีร์ · Mjölnir", "ธอร์", "ด้ามสั้น ขว้างไม่พลาด บินกลับมาเอง เอ็ดดาของสนอร์รี", "hammer"],
["กุงนีร์ · Gungnir", "โอดิน", "หอกฝีมือลูก ๆ ของอีวัลดี จากการประชันครั้งเดียวกับค้อน", "spear"],
["กระบองวิเศษ · Ruyi Jingu Bang", "ซุนหงอคง", "13,500 ชั่ง ย่อขยายได้ตามสั่ง ไซอิ๋ว ตอนที่ 3", "staff"],
["ขวานรามสูร · Ramasun's axe", "รามสูร", "ขว้างใส่เมขลา เสียงขวานคือฟ้าร้อง นาฏศิลป์และจิตรกรรมไทย", "axe"],
["แก้วมณีเมขลา · Mekhala's jewel", "เมขลา", "ล่อแสงแยงตายักษ์ แสงแก้วคือฟ้าแลบ", "jewel"],
["พรหมาสตร์ · Brahmastra", "พระพรหม", "อาวุธที่เรียกมาด้วยมนต์ แรงเกินกว่าจะใช้เล่น ๆ มหาภารตะ", "astra"],
["คาณฑีวะ · Gandiva", "อรชุน", "ธนูที่อรชุนได้จากพระอัคนี ก่อนเผาป่าขาณฑวะ มหาภารตะ", "bow"],
["คุซานางิ · Kusanagi", "ซูซาโนะโอะ", "ดาบที่พบในหางงูแปดหัวโอโรจิ โคจิกิ ปี 712", "sword"]],

"words_h": "คำศัพท์",
"src_h": "แหล่งข้อมูล",
"src_p": "เรื่องเล่ามาจากคำแปลของคัมภีร์ที่ระบุ ตัวเลขมาจากงานวิจัยและหน่วยงานข้างล่าง ภาพจากวิกิมีเดียคอมมอนส์ พร้อมสัญญาอนุญาตของแต่ละภาพ",
"foot": "เนื้อหา CC BY 4.0, NaNoBotCo โค้ด MIT ภาพถ่ายใช้สัญญาอนุญาตของแต่ละภาพ",
"js": {"sym": "{n}°", "km": "กม.", "mi": "ไมล์", "s": "วินาที", "us": "ไมโครวินาที", "cm": "ซม.", "m": "ม.", "kgm3": "กก./ลบ.ม.",
 "like": [[0.01, "อากาศเบาบาง"], [1.2, "อากาศ"], [100, "ไม้ก๊อก"], [1000, "น้ำ"], [2700, "อะลูมิเนียม"], [7874, "เหล็ก"], [19300, "ทองคำ"], [22590, "ออสเมียม โลหะที่แน่นที่สุด"], [1e5, "ไม่มีอะไรบนโลก"], [1e7, "ชั้นนอกของดาวแคระขาว"], [1e9, "แกนดาวแคระขาว"], [1e14, "เกินดาวแคระขาว"], [4e17, "ดาวนิวตรอน"]],
 "tap": "แตะ", "wait": "ดูท้องฟ้า…", "again": "อีกครั้ง", "hit": "โดน!", "miss": "ไฟมอด", "fly": "แมลงวันกัด", "done": "เสร็จ", "ring": "สั่นกระดิ่ง"}
}}

# en, th, en-gloss, th-gloss
WORDS = [
("Vajra", "วชิระ / วัชระ", "Sanskrit for thunderbolt and for diamond; Indra's weapon, and a Buddhist ritual tool.", "ภาษาสันสกฤต แปลว่าสายฟ้าและเพชร อาวุธของพระอินทร์ และเครื่องมือพิธีในพุทธ"),
("Dorje", "ดอร์เจ", "Tibetan word for the vajra.", "คำทิเบตที่เรียกวชิระ"),
("Ghanta, drilbu", "ฆัณฏา, ดริลบุ", "The ritual bell held with the vajra; Sanskrit and Tibetan names.", "กระดิ่งที่ถือคู่กับวชิระ ชื่อสันสกฤตและทิเบต"),
("Vajrayana", "วัชรยาน", "\"Diamond vehicle\": the Buddhism of Tibet, Nepal, Mongolia and Japan's Shingon school.", "\"ยานเพชร\" พุทธศาสนาแบบทิเบต เนปาล มองโกเลีย และนิกายชินงอนของญี่ปุ่น"),
("Vritra", "วฤตระ", "The serpent who held back the waters in the Rigveda; Indra killed him with the vajra.", "งูยักษ์ที่กักน้ำไว้ในฤคเวท พระอินทร์ฆ่าด้วยวชิระ"),
("Return stroke", "จังหวะย้อนกลับ", "The bright flash that runs back up the channel once a lightning leader touches ground.", "แสงจ้าที่วิ่งย้อนขึ้นไปตามช่อง เมื่อสายฟ้านำทางแตะพื้น"),
("Fractal dimension", "มิติแฟร็กทัล", "A number between 1 and 2 for a branching line: how much of the plane it fills as you look closer.", "ตัวเลขระหว่าง 1 กับ 2 ของเส้นที่แตกกิ่ง บอกว่ามันเต็มพื้นที่แค่ไหนเมื่อมองใกล้ขึ้น"),
("Fulgurite", "ฟัลกูไรต์", "A tube of glass made where lightning melts sand or soil.", "หลอดแก้วที่เกิดเมื่อฟ้าผ่าหลอมทรายหรือดิน"),
("Thunderstone, ceraunia", "ขวานฟ้า", "A prehistoric stone axe believed to have fallen with lightning, kept as a charm.", "ขวานหินยุคก่อนประวัติศาสตร์ ที่เชื่อว่าตกลงมากับฟ้าผ่า เก็บไว้เป็นเครื่องราง"),
("Meteoritic iron", "เหล็กอุกกาบาต", "Iron-nickel metal that fell from space; Earth iron from ore has far less nickel.", "โลหะเหล็กนิกเกิลที่ตกมาจากอวกาศ เหล็กจากแร่บนโลกมีนิกเกิลน้อยกว่ามาก"),
("Widmanstätten pattern", "ลายวิดมันชเตตเทิน", "Criss-cross crystal bands in etched iron meteorites, grown by very slow cooling.", "แถบผลึกไขว้กันในอุกกาบาตเหล็กที่กัดกรด เกิดจากการเย็นตัวช้ามาก"),
("Sudarshana chakra", "จักรสุทรรศน์", "Vishnu's spinning discus.", "จักรหมุนของพระนารายณ์"),
("Trishula", "ตรีศูล", "Shiva's trident.", "สามง่ามของพระศิวะ"),
("Jin, catty", "ชั่ง", "A Chinese weight; about 600 g in the Ming dynasty, 500 g today.", "หน่วยน้ำหนักจีน สมัยหมิงราว 600 กรัม ปัจจุบัน 500 กรัม"),
("Limaçon", "ลิมาซง", "A looping curve r = b + a·cos θ; here, the path of a hammer that comes back.", "เส้นโค้งเป็นวง r = b + a·cos θ ในที่นี้คือทางของค้อนที่บินกลับ"),
]

SOURCES = [
("Wikipedia: Vajra", "https://en.wikipedia.org/wiki/Vajra"),
("Wikipedia: Vritra", "https://en.wikipedia.org/wiki/Vritra"),
("Wikipedia: Dadhichi", "https://en.wikipedia.org/wiki/Dadhichi"),
("Wikipedia: Ghanta", "https://en.wikipedia.org/wiki/Ghanta"),
("Wikipedia: Diamond Sutra", "https://en.wikipedia.org/wiki/Diamond_Sutra"),
("Wikipedia: Vajrapani", "https://en.wikipedia.org/wiki/Vajrapani"),
("Thailex: วชิราวุธ, and Mekhala", "https://www.thailex.info/THAILEX/THAILEXENG/LEXICON/W.HTM"),
("Niemeyer, Pietronero & Wiesmann (1984), Fractal dimension of dielectric breakdown, Phys. Rev. Lett. 52, 1033", "https://doi.org/10.1103/PhysRevLett.52.1033"),
("Yale Fractal Geometry: the dielectric breakdown model", "https://gauss.math.yale.edu/public_html/People/frame/Fractals/Panorama/Physics/DLA/DBM/DBM.html"),
("National Geographic: Flash facts about lightning", "https://www.nationalgeographic.com/science/article/flash-facts-about-lightning"),
("ศิลปวัฒนธรรม: เมขลา-รามสูร กับ ขวานรามสูร", "https://www.silpa-mag.com/culture/article_18139"),
("ศิลปวัฒนธรรม: อดีตชาติของรามสูร ผู้มีขวานเป็นอาวุธ", "https://www.silpa-mag.com/history/article_15716"),
("Wikipedia: Manimekhala", "https://en.wikipedia.org/wiki/Manimekhala"),
("Wikipedia: List of storms named Rammasun", "https://en.wikipedia.org/wiki/List_of_storms_named_Rammasun"),
("Wikipedia: List of storms named Mekkhala", "https://en.wikipedia.org/wiki/List_of_storms_named_Mekkhala"),
("Wikipedia: Thunderstone (folklore)", "https://en.wikipedia.org/wiki/Thunderstone_(folklore)"),
("Royal Institute dictionary entry ขวานฟ้า, via wichaa's lexicon", "https://wichaa.net/"),
("Comelli et al. (2016), The meteoritic origin of Tutankhamun's iron dagger blade, Meteoritics & Planetary Science 51, 1301", "https://doi.org/10.1111/maps.12664"),
("Eos: Pharaoh's iron dagger made from a meteorite", "https://eos.org/articles/pharaohs-iron-dagger-made-from-a-meteorite-study-confirms"),
("Wikipedia: Widmanstätten pattern", "https://en.wikipedia.org/wiki/Widmanst%C3%A4tten_pattern"),
("Vishnu Purana, Book 3 Chapter 2, trans. H. H. Wilson", "https://sacred-texts.com/hin/vp/vp076.htm"),
("Wikipedia: Sudarshana Chakra", "https://en.wikipedia.org/wiki/Sudarshana_Chakra"),
("Wikipedia: Chakri dynasty", "https://en.wikipedia.org/wiki/Chakri_dynasty"),
("Hesiod, Theogony, trans. A. S. Kline", "https://poetryintranslation.com/PITBR/Greek/HesiodTheogony.php"),
("Wikipedia: Sindri (mythology) — Skáldskaparmál's forging contest", "https://en.wikipedia.org/wiki/Sindri_(mythology)"),
("Wikipedia: Ruyi Jingu Bang", "https://en.wikipedia.org/wiki/Ruyi_Jingu_Bang"),
("Journey to the West Research: the weight of the Monkey King's staff", "https://journeytothewestresearch.com/tag/13/"),
("Wikipedia: Gungnir", "https://en.wikipedia.org/wiki/Gungnir"),
("Wikipedia: Gandiva", "https://en.wikipedia.org/wiki/Gandiva"),
("Wikipedia: Brahmastra", "https://en.wikipedia.org/wiki/Brahmastra"),
("Wikipedia: Kusanagi", "https://en.wikipedia.org/wiki/Kusanagi"),
("วิกิพีเดีย: วชิระ", "https://th.wikipedia.org/wiki/%E0%B8%A7%E0%B8%8A%E0%B8%B4%E0%B8%A3%E0%B8%B0"),
("Wikimedia Commons", "https://commons.wikimedia.org/"),
]
